#ifndef MIDI_NOTES_H
# define MIDI_NOTES_H

enum e_notes{
	A0 = 21,
	AS0,
	B0,

	C1,
	CS1,
	D1,
	DS1,
	E1,
	F1,
	FS1,
	G1,
	GS1,
	A1,
	AS1,
	B1,

	C2,
	CS2,
	D2,
	DS2,
	E2,
	F2,
	FS2,
	G2,
	GS2,
	A2,
	AS2,
	B2,

	C3,
	CS3,
	D3,
	DS3,
	E3,
	F3,
	FS3,
	G3,
	GS3,
	A3,
	AS3,
	B3,

	C4,
	CS4,
	D4,
	DS4,
	E4,
	F4,
	FS4,
	G4,
	GS4,
	A4,
	AS4,
	B4,

	C5,
	CS5,
	D5,
	DS5,
	E5,
	F5,
	FS5,
	G5,
	GS5,
	A5,
	AS5,
	B5,

	C6,
	CS6,
	D6,
	DS6,
	E6,
	F6,
	FS6,
	G6,
	GS6,
	A6,
	AS6,
	B6,

	C7,
	CS7,
	D7,
	DS7,
	E7,
	F7,
	FS7,
	G7,
	GS7,
	A7,
	AS7,
	B7,

	C8,
	CS8,
	D8,
	DS8,
	E8,
	F8,
	FS8,
	G8,
	GS8,
	A8,
	AS8,
	B8,

	C9,
	CS9,
	D9,
	DS9,
	E9,
	F9,
	FS9,
	G9,
	GS9,
};

typedef struct	s_note_definition
{
	uint8_t		note;
	char 		*name;
}				t_note_definition;

static const t_note_definition g_notes_definitions[] = 
{
	(t_note_definition){.note = A0, .name = "A0"},
	(t_note_definition){.note = AS0, .name = "AS0"},
	(t_note_definition){.note = B0, .name = "B0"},

	(t_note_definition){.note = C1, .name = "C1"},
	(t_note_definition){.note = CS1, .name = "CS1"},
	(t_note_definition){.note = D1, .name = "D1"},
	(t_note_definition){.note = DS1, .name = "DS1"},
	(t_note_definition){.note = E1, .name = "E1"},
	(t_note_definition){.note = F1, .name = "F1"},
	(t_note_definition){.note = FS1, .name = "FS1"},
	(t_note_definition){.note = G1, .name = "G1"},
	(t_note_definition){.note = GS1, .name = "GS1"},
	(t_note_definition){.note = A1, .name = "A1"},
	(t_note_definition){.note = AS1, .name = "AS1"},
	(t_note_definition){.note = B1, .name = "B1"},

	(t_note_definition){.note = C2, .name = "C2"},
	(t_note_definition){.note = CS2, .name = "CS2"},
	(t_note_definition){.note = D2, .name = "D2"},
	(t_note_definition){.note = DS2, .name = "DS2"},
	(t_note_definition){.note = E2, .name = "E2"},
	(t_note_definition){.note = F2, .name = "F2"},
	(t_note_definition){.note = FS2, .name = "FS2"},
	(t_note_definition){.note = G2, .name = "G2"},
	(t_note_definition){.note = GS2, .name = "GS2"},
	(t_note_definition){.note = A2, .name = "A2"},
	(t_note_definition){.note = AS2, .name = "AS2"},
	(t_note_definition){.note = B2, .name = "B2"},

	(t_note_definition){.note = C3, .name = "C3"},
	(t_note_definition){.note = CS3, .name = "CS3"},
	(t_note_definition){.note = D3, .name = "D3"},
	(t_note_definition){.note = DS3, .name = "DS3"},
	(t_note_definition){.note = E3, .name = "E3"},
	(t_note_definition){.note = F3, .name = "F3"},
	(t_note_definition){.note = FS3, .name = "FS3"},
	(t_note_definition){.note = G3, .name = "G3"},
	(t_note_definition){.note = GS3, .name = "GS3"},
	(t_note_definition){.note = A3, .name = "A3"},
	(t_note_definition){.note = AS3, .name = "AS3"},
	(t_note_definition){.note = B3, .name = "B3"},

	(t_note_definition){.note = C4, .name = "C4"},
	(t_note_definition){.note = CS4, .name = "CS4"},
	(t_note_definition){.note = D4, .name = "D4"},
	(t_note_definition){.note = DS4, .name = "DS4"},
	(t_note_definition){.note = E4, .name = "E4"},
	(t_note_definition){.note = F4, .name = "F4"},
	(t_note_definition){.note = FS4, .name = "FS4"},
	(t_note_definition){.note = G4, .name = "G4"},
	(t_note_definition){.note = GS4, .name = "GS4"},
	(t_note_definition){.note = A4, .name = "A4"},
	(t_note_definition){.note = AS4, .name = "AS4"},
	(t_note_definition){.note = B4, .name = "B4"},

	(t_note_definition){.note = C5, .name = "C5"},
	(t_note_definition){.note = CS5, .name = "CS5"},
	(t_note_definition){.note = D5, .name = "D5"},
	(t_note_definition){.note = DS5, .name = "DS5"},
	(t_note_definition){.note = E5, .name = "E5"},
	(t_note_definition){.note = F5, .name = "F5"},
	(t_note_definition){.note = FS5, .name = "FS5"},
	(t_note_definition){.note = G5, .name = "G5"},
	(t_note_definition){.note = GS5, .name = "GS5"},
	(t_note_definition){.note = A5, .name = "A5"},
	(t_note_definition){.note = AS5, .name = "AS5"},
	(t_note_definition){.note = B5, .name = "B5"},

	(t_note_definition){.note = C6, .name = "C6"},
	(t_note_definition){.note = CS6, .name = "CS6"},
	(t_note_definition){.note = D6, .name = "D6"},
	(t_note_definition){.note = DS6, .name = "DS6"},
	(t_note_definition){.note = E6, .name = "E6"},
	(t_note_definition){.note = F6, .name = "F6"},
	(t_note_definition){.note = FS6, .name = "FS6"},
	(t_note_definition){.note = G6, .name = "G6"},
	(t_note_definition){.note = GS6, .name = "GS6"},
	(t_note_definition){.note = A6, .name = "A6"},
	(t_note_definition){.note = AS6, .name = "AS6"},
	(t_note_definition){.note = B6, .name = "B6"},

	(t_note_definition){.note = C7, .name = "C7"},
	(t_note_definition){.note = CS7, .name = "CS7"},
	(t_note_definition){.note = D7, .name = "D7"},
	(t_note_definition){.note = DS7, .name = "DS7"},
	(t_note_definition){.note = E7, .name = "E7"},
	(t_note_definition){.note = F7, .name = "F7"},
	(t_note_definition){.note = FS7, .name = "FS7"},
	(t_note_definition){.note = G7, .name = "G7"},
	(t_note_definition){.note = GS7, .name = "GS7"},
	(t_note_definition){.note = A7, .name = "A7"},
	(t_note_definition){.note = AS7, .name = "AS7"},
	(t_note_definition){.note = B7, .name = "B7"},

	(t_note_definition){.note = C8, .name = "C8"},
	(t_note_definition){.note = CS8, .name = "CS8"},
	(t_note_definition){.note = D8, .name = "D8"},
	(t_note_definition){.note = DS8, .name = "DS8"},
	(t_note_definition){.note = E8, .name = "E8"},
	(t_note_definition){.note = F8, .name = "F8"},
	(t_note_definition){.note = FS8, .name = "FS8"},
	(t_note_definition){.note = G8, .name = "G8"},
	(t_note_definition){.note = GS8, .name = "GS8"},
	(t_note_definition){.note = A8, .name = "A8"},
	(t_note_definition){.note = AS8, .name = "AS8"},
	(t_note_definition){.note = B8, .name = "B8"},

	(t_note_definition){.note = C9, .name = "C9"},
	(t_note_definition){.note = CS9, .name = "CS9"},
	(t_note_definition){.note = D9, .name = "D9"},
	(t_note_definition){.note = DS9, .name = "DS9"},
	(t_note_definition){.note = E9, .name = "E9"},
	(t_note_definition){.note = F9, .name = "F9"},
	(t_note_definition){.note = FS9, .name = "FS9"},
	(t_note_definition){.note = G9, .name = "G9"},
	(t_note_definition){.note = GS9, .name = "GS9"}
};

#endif